name: sample-nodejs-app
run-name: ${{ github.actor }}
on: 
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
    Docker-CI:
      runs-on: ubuntu-latest
      # steps:
      
      #   -
      #     name: Login to DockerHub
      #     env:
      #       DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      #       DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      #     run: docker --version && docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      #   - name: Build Docker Image
      #     run: docker build . -f Dockerfile -t sample-node-app:latest
      #   -
      #     name: Push to DockerHub
      #     run: docker push ${{secrets.DOCKERHUB_USERNAME}}/sample-node-app
      steps:
        - uses: actions/checkout@v2
        - name: Login
          run:  docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin docker.io
