name: sample-nodejs-app
run-name: ${{ github.actor }}
on: 
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
    Docker-CI:
      runs-on: ubuntu-latest
      steps:
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
          # env:
          #   DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          #   DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          # run: docker --version && echo "$DOCKERHUB_USERNAME" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
        # - name: Build Docker Image
        #   run: docker build . -f Dockerfile -t sample-node-app:latest
        - name: Build and push
          uses: docker/build-push-action@v3
          with:
            context: .
            file: Dockerfile
            push: true
            tags: user/app:latest
        -
          name: Push to DockerHub
          run: docker push ${{secrets.DOCKERHUB_USERNAME}}/sample-node-app
